spring:
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    url: jdbc:postgresql://postgresql:5432/CurrencyDB
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

jwt:
  token:
    access:
      secret-key: Konstantin
    refresh:
      secret-key: Kharchenko

lifetime:
  access:
    token: 180
  refresh:
    token: 240

github:
  client-id: client-id
  client-secret: client-secret
  register:
    uri:  http://api-gateway-service:8080/registration/github

facebook:
  client-id: client-id
  client-secret: client-secret
  register:
    uri:  http://api-gateway-service:8080/registration/facebook

google:
  client-id: google-id
  client-secret: google-secret

code:
  client-id: client-id
  client-secret: client-secret

front:
  redirect-uri:
